#!/usr/bin/env python3
"""Generate the warp menu's 8x8 bitmap font as a C array.

The menu used to draw its text with pspDebugScreen, i.e. the CPU poking pixels
straight into the framebuffer. That works on real hardware but is invisible in
PPSSPP, which renders into a GPU texture and does not read CPU framebuffer
writes back by default -- so the menu appeared as a bare backdrop with no text.
Drawing the glyphs as GE sprites instead works in both places.

One bit per pixel, 8 bytes per glyph, ASCII 32..126. Expanded to a texture atlas
at runtime rather than shipped as one: 95 glyphs * 8 bytes = 760 bytes of source
against 32 KB for an RGBA atlas, and the expansion is a few hundred
microseconds, once.

Usage: gen_menu_font.py <output.inc>
"""
import sys

from PIL import Image, ImageDraw, ImageFont

FIRST, LAST = 32, 126
CELL = 8
FONT_PATHS = [
    "/usr/share/fonts/dejavu/DejaVuSansMono-Bold.ttf",
    "/usr/share/fonts/dejavu/DejaVuSansMono.ttf",
    "/run/host/fonts/truetype/liberation/LiberationMono-Bold.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf",
]


def load_font():
    for p in FONT_PATHS:
        try:
            # 9px lands closest to filling an 8px cell without clipping
            # descenders on this family; verified against the rendered rows.
            return ImageFont.truetype(p, 9), p
        except OSError:
            continue
    raise SystemExit("gen_menu_font.py: no usable monospace TTF found")


def main(outpath):
    font, used = load_font()
    rows = []

    for code in range(FIRST, LAST + 1):
        img = Image.new("L", (CELL, CELL), 0)
        d = ImageDraw.Draw(img)
        # -1 on y pulls the baseline up so caps fit inside 8 rows.
        d.text((0, -1), chr(code), font=font, fill=255)
        px = img.load()

        glyph = []
        for y in range(CELL):
            bits = 0
            for x in range(CELL):
                if px[x, y] >= 112:          # midpoint threshold
                    bits |= 0x80 >> x
            glyph.append(bits)
        rows.append((code, glyph))

    with open(outpath, "w") as f:
        f.write("/* Generated by psp/tools/gen_menu_font.py -- do not edit.\n")
        f.write(" * Source font: %s at 9px, thresholded to 1bpp.\n" % used)
        f.write(" * ASCII %d..%d, 8 bytes per glyph, MSB = leftmost pixel.\n */\n" % (FIRST, LAST))
        for code, glyph in rows:
            ch = chr(code)
            label = "space" if ch == " " else ("backslash" if ch == "\\" else ch)
            f.write("    " + ", ".join("0x%02X" % b for b in glyph) + ", /* %s */\n" % label)

    print("gen_menu_font: %d glyphs -> %s" % (len(rows), outpath))


if __name__ == "__main__":
    main(sys.argv[1])
