#!/usr/bin/env python3
"""Emit the scene textures that z_scene_table.c references by C symbol.

WHY THIS EXISTS
---------------
src/code/z_scene_table.c reaches a handful of textures directly by name -- the
day/night entrance views, the Kakariko and Lon Lon window panes, the Gerudo
Fortress walls, Dodongo's Cavern's eight-frame animated lava floor. On the N64
those symbols live inside the SCENE files, which this port loads at runtime as
native blobs rather than compiling in. So nothing defined them, and they were
papered over with 64-byte placeholders in psp/src/phase2_stubs_gen.c:

    char gDCLavaFloor1Tex[64];

That is not merely "no texture". The display list loads a full texture from that
address -- 32x32 at 8bpp is 1 KB -- so the loader reads a kilobyte starting at a
64-byte object and hands the GE whatever globals follow it. Measured symptoms:
Dodongo's Cavern's lava as one flat grey-violet sheet with a dashed line of red,
orange and cyan pixels along its edges, and a band of confetti-coloured pixels
across the walls of Kakariko and Lon Lon Ranch -- and those are the only two
scenes in the game whose draw config binds a window texture.

WHAT IT DOES
------------
The scene .c files already contain exactly the definition needed, e.g.

    u64 gDCLavaFloor1Tex[TEX_LEN(u64, gDCLavaFloor1Tex_WIDTH, gDCLavaFloor1Tex_HEIGHT, 8)] = {
    #include "assets/scenes/dungeons/ddan/gDCLavaFloor1Tex.ci8.tlut_gDCRoom0TLUT.inc.c"
    };

so this script does not invent anything: it copies those blocks out of the scene
sources into one translation unit. The array length is written as a plain number
instead of the TEX_LEN macro so the output needs no scene headers.

The palettes stay where they are. These are CI8 textures whose TLUT is loaded
from the scene's own segment by the display list, which is unaffected.

Usage: gen_scene_textures.py <repo-root> <output.c>
"""
import os
import re
import sys


def referenced_symbols(root):
    """Texture symbols that src/code/z_scene_table.c reaches by name.

    The list is taken from the CONSUMER, not from the placeholder file it used
    to come from. That was circular: emptying the placeholders emptied the list,
    and the next build linked nothing. z_scene_table.c is the reason these
    symbols have to exist at all, so it is the honest source of truth -- add a
    scene draw config that names a new texture and this picks it up.
    """
    path = os.path.join(root, "src", "code", "z_scene_table.c")
    text = open(path).read()
    # Both spellings the file uses: bare references inside the void* tables, and
    # the extern declarations at the top.
    return set(re.findall(r"\b(g[A-Za-z0-9_]+Tex)\b", text))


def find_definitions(root, wanted):
    """{symbol: (bytes_per_texel_code, width, height, include_path)}"""
    scenes = os.path.join(root, "extracted", "pal-1.0", "assets", "scenes")
    dims = {}
    defs = {}

    for dirpath, _dirs, files in os.walk(scenes):
        for f in files:
            if not f.endswith((".c", ".h")):
                continue
            text = open(os.path.join(dirpath, f), errors="ignore").read()
            for m in re.finditer(r"#define (g[A-Za-z0-9_]+Tex)_(WIDTH|HEIGHT) (\d+)", text):
                if m.group(1) in wanted:
                    dims.setdefault(m.group(1), {})[m.group(2)] = int(m.group(3))
            for m in re.finditer(
                    r"u64 (g[A-Za-z0-9_]+Tex)\[TEX_LEN\(u64, [^,]+, [^,]+, (\d+)\)\] = \{\s*\n"
                    r'#include "([^"]+)"', text):
                if m.group(1) in wanted:
                    defs[m.group(1)] = (int(m.group(2)), m.group(3))

    out = {}
    for sym, (bits, inc) in defs.items():
        d = dims.get(sym)
        if d is None or "WIDTH" not in d or "HEIGHT" not in d:
            continue
        out[sym] = (bits, d["WIDTH"], d["HEIGHT"], inc)
    return out


def main():
    root, outpath = sys.argv[1], sys.argv[2]
    wanted = referenced_symbols(root)
    found = find_definitions(root, wanted)
    missing = sorted(wanted - set(found))

    with open(outpath, "w") as out:
        out.write("/* GENERATED by psp/tools/gen_scene_textures.py -- do not edit.\n"
                  " *\n"
                  " * The scene textures z_scene_table.c names directly. See the script's\n"
                  " * docstring for why they cannot come from the scene blobs, and for what\n"
                  " * the 64-byte placeholders they replace actually rendered.\n"
                  " */\n"
                  '#include "ultra64.h"\n\n')
        for sym in sorted(found):
            bits, w, h, inc = found[sym]
            words = w * h * bits // 8 // 8   # bytes / sizeof(u64)
            out.write("/* %s: %ux%u @ %ubpp -> %u bytes */\n" % (sym, w, h, bits, words * 8))
            out.write("u64 %s[%u] = {\n#include \"%s\"\n};\n\n" % (sym, words, inc))

    print("%d of %d symbols emitted -> %s" % (len(found), len(wanted), outpath))
    if missing:
        print("NOT in the scene sources (handle separately): %s" % ", ".join(missing))
    if not found:
        sys.exit("gen_scene_textures.py: found nothing -- refusing to write an "
                 "empty file that would link as undefined symbols")


if __name__ == "__main__":
    main()
